--CREATE DATABASE	AUCA_2

USE AUCA_2

--DROP TABLE [User]

/*
CREATE TABLE [User] (
	ID INT CONSTRAINT PK__User PRIMARY KEY CLUSTERED,
	[Name] NVARCHAR(255)
);
GO

DECLARE @counter INT = 0;

WHILE @counter < 1000
BEGIN 
	INSERT INTO [User] (ID, [Name])	VALUES (@counter, CAST(NEWID() AS NVARCHAR(255)));
	SET @counter += 1;
END
*/

--SELECT * FROM [User]

SET STATISTICS IO ON

SELECT * FROM [User] WHERE [Name] LIKE 'A%'

SET STATISTICS IO OFF

--CREATE NONCLUSTERED INDEX IX_User_Name ON [User] ([Name])